// @license
// Copyright (c) 2025 Göran Hegenberg. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_log/gg_log.dart';
import 'package:path/path.dart' as path;

/// Marker that identifies a `pre-push` hook as one `gg` installed itself.
///
/// Earlier versions of `gg do add` wrote a `pre-push` hook that shelled out to
/// `dart run .gg/verify_push.dart`, which blocked a push to `main`/`master`
/// unless `gg did commit` confirmed a clean tree. Pushing to `main` is now
/// blocked by the remote and all merges go through pull requests, so the hook
/// is obsolete — but it still sits in the `.git/hooks` directory of every
/// checkout that ever ran an older `gg do add`.
const String legacyPrePushMarker = '.gg/verify_push.dart';

/// Removes the obsolete `gg`-generated pre-push hook from [repoDir].
///
/// Deletes two files, both of which are untracked (`.git/hooks` is never
/// tracked and `.gg/verify_push.dart` is covered by the `.gg/*` gitignore
/// rule), so the removal never dirties the working tree:
///
/// - `.git/hooks/pre-push` — **only** when its content references
///   [legacyPrePushMarker]. A hook the user wrote themselves does not carry
///   the marker and is left untouched.
/// - `.gg/verify_push.dart` — the script the hook invoked. It is generated by
///   `gg` alone, so it is removed unconditionally.
///
/// Returns `true` when at least one file was deleted.
bool removeLegacyGitHooks({required Directory repoDir, required GgLog ggLog}) {
  final repoName = path.basename(repoDir.path);
  var removedSomething = false;

  // Remove the hook itself, but never a hook the user wrote themselves.
  final prePushHook = File(
    path.join(repoDir.path, '.git', 'hooks', 'pre-push'),
  );

  if (prePushHook.existsSync()) {
    if (prePushHook.readAsStringSync().contains(legacyPrePushMarker)) {
      prePushHook.deleteSync();
      removedSomething = true;
    } else {
      ggLog(
        'Keeping the custom pre-push hook of $repoName — it is not the hook '
        'generated by gg.',
      );
    }
  }

  // Remove the script the hook ran.
  final verifyPush = File(path.join(repoDir.path, '.gg', 'verify_push.dart'));

  if (verifyPush.existsSync()) {
    verifyPush.deleteSync();
    removedSomething = true;
  }

  if (removedSomething) {
    ggLog('Removed the obsolete gg pre-push hook from $repoName.');
  }

  return removedSomething;
}
