// @license
// Copyright (c) 2019 - 2025 Dr. Gabriel Gatzsche. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_localize_refs/gg_localize_refs.dart';
import 'package:gg_multi_workspace/src/backend/dependency_overrides.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';

void main() {
  late Directory tempDir;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('dependency_overrides_test_');
  });

  tearDown(() {
    if (tempDir.existsSync()) tempDir.deleteSync(recursive: true);
  });

  Directory repo(String name, [String? overrides]) {
    final dir = Directory(path.join(tempDir.path, name))..createSync();
    if (overrides != null) {
      File(
        path.join(dir.path, pubspecOverridesFileName),
      ).writeAsStringSync(overrides);
    }
    return dir;
  }

  String overridesOf(Directory dir) =>
      File(path.join(dir.path, pubspecOverridesFileName)).readAsStringSync();

  bool hasOverrides(Directory dir) =>
      File(path.join(dir.path, pubspecOverridesFileName)).existsSync();

  group('removeDependencyOverrides', () {
    test('removes the entry and keeps the remaining ones', () {
      final a = repo('a', '''
# Generated by gg_localize_refs.
dependency_overrides:
  b:
    path: ../b
  c:
    path: ../c
''');

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(overridesOf(a), contains('c:'));
      expect(overridesOf(a), isNot(contains('../b')));
      // The header comment of gg_localize_refs survives the edit.
      expect(overridesOf(a), contains('# Generated by gg_localize_refs.'));
    });

    test('deletes the file when nothing would be left to override', () {
      final a = repo('a', '''
dependency_overrides:
  b:
    path: ../b
''');

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(hasOverrides(a), isFalse);
    });

    test('touches only the repos that reference the removed package', () {
      final a = repo('a', 'dependency_overrides:\n  b:\n    path: ../b\n');
      final c = repo('c', 'dependency_overrides:\n  d:\n    path: ../d\n');

      final changed = removeDependencyOverrides(
        repoDirs: [a, c],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(hasOverrides(c), isTrue);
    });

    test('returns nothing when no names are given', () {
      final a = repo('a', 'dependency_overrides:\n  b:\n    path: ../b\n');
      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: const {}),
        isEmpty,
      );
      expect(hasOverrides(a), isTrue);
    });

    test('skips a repo without pubspec_overrides.yaml', () {
      final a = repo('a');
      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
    });

    test('skips a file without a dependency_overrides map', () {
      final a = repo('a', 'dependency_overrides:\n');
      final b = repo('b', 'other: value\n');

      expect(
        removeDependencyOverrides(repoDirs: [a, b], packageNames: {'x'}),
        isEmpty,
      );
      expect(hasOverrides(a), isTrue);
      expect(hasOverrides(b), isTrue);
    });

    test('skips a file that is no YAML map', () {
      final a = repo('a', '- just\n- a list\n');
      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
      expect(hasOverrides(a), isTrue);
    });

    test('leaves an unparsable file alone', () {
      const broken = "dependency_overrides:\n  b: 'unterminated\n";
      final a = repo('a', broken);

      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
      expect(overridesOf(a), broken);
    });
  });

  group('removeDependencyOverrides — pnpm-workspace.yaml', () {
    File pnpmFileOf(Directory dir) =>
        File(path.join(dir.path, 'pnpm-workspace.yaml'));

    Directory tsRepo(String name, String pnpmWorkspace) {
      final dir = Directory(path.join(tempDir.path, name))..createSync();
      pnpmFileOf(dir).writeAsStringSync(pnpmWorkspace);
      return dir;
    }

    test('removes the link override of the deleted repo', () {
      final a = tsRepo(
        'a',
        'allowBuilds:\n  esbuild: true\n'
            'overrides:\n  b: link:../b\n  c: link:../c\n',
      );

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      final content = pnpmFileOf(a).readAsStringSync();
      expect(content, isNot(contains('link:../b')));
      // Only the named entry goes. `c` was not removed from the ticket, so
      // its override stays — as does the foreign `allowBuilds` setting.
      expect(content, contains('link:../c'));
      expect(content, contains('allowBuilds'));
    });

    test('keeps the link overrides of the repos that stay in the ticket', () {
      // The regression: `c` is still checked out next to `a` and its
      // override is gg-owned — exactly the shape the ownership sweep of
      // `removeOwnedOverrides` would have taken along with `b`.
      final c = Directory(path.join(tempDir.path, 'c'))..createSync();
      File(
        path.join(c.path, 'package.json'),
      ).writeAsStringSync('{"name": "c"}');

      final a = tsRepo('a', 'overrides:\n  b: link:../b\n  c: link:../c\n');

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      final content = pnpmFileOf(a).readAsStringSync();
      expect(content, isNot(contains('link:../b')));
      expect(content, contains('c: link:../c'));
    });

    test('deletes a file gg created once nothing is left', () {
      final a = tsRepo(
        'a',
        '${PnpmWorkspaceIo.headerComment}overrides:\n  b: link:../b\n',
      );

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(pnpmFileOf(a).existsSync(), isFalse);
    });

    test('leaves an unparsable pnpm-workspace.yaml alone', () {
      const broken = 'overrides: [pnpm\n';
      final a = tsRepo('a', broken);

      expect(
        removeDependencyOverrides(repoDirs: [a], packageNames: {'b'}),
        isEmpty,
      );
      expect(pnpmFileOf(a).readAsStringSync(), broken);
    });

    test('changes both files of a bridge repo in one pass', () {
      final a = repo('a', 'dependency_overrides:\n  b:\n    path: ../b\n');
      pnpmFileOf(a).writeAsStringSync('overrides:\n  b: link:../b\n');

      final changed = removeDependencyOverrides(
        repoDirs: [a],
        packageNames: {'b'},
      );

      expect(changed, [a]);
      expect(hasOverrides(a), isFalse);
      // The pnpm file carries no gg header, so ownership of the file itself
      // cannot be proven — it stays, with the overrides section removed.
      final pnpmContent = pnpmFileOf(a).readAsStringSync();
      expect(pnpmContent, isNot(contains('link:')));
    });
  });
}
