// @license
// Copyright (c) 2025 Göran Hegenberg. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_multi_workspace/src/backend/legacy_git_hooks.dart';
import 'package:path/path.dart' as path;
import 'package:test/test.dart';

void main() {
  late Directory tmp;
  late Directory repoDir;
  late List<String> messages;

  /// The pre-push hook older gg versions installed.
  const ggHook = '#!/bin/sh\nset -e\n\ndart run .gg/verify_push.dart';

  setUp(() {
    tmp = Directory.systemTemp.createTempSync('legacy_git_hooks_test');
    repoDir = Directory(path.join(tmp.path, 'my_repo'))
      ..createSync(recursive: true);
    messages = <String>[];
  });

  tearDown(() {
    if (tmp.existsSync()) {
      tmp.deleteSync(recursive: true);
    }
  });

  File prePushHook() =>
      File(path.join(repoDir.path, '.git', 'hooks', 'pre-push'));

  File verifyPush() => File(path.join(repoDir.path, '.gg', 'verify_push.dart'));

  void writePrePushHook(String content) {
    final file = prePushHook();
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
  }

  void writeVerifyPush() {
    final file = verifyPush();
    file.parent.createSync(recursive: true);
    file.writeAsStringSync('void main() {}');
  }

  group('removeLegacyGitHooks', () {
    test('removes the gg pre-push hook and verify_push.dart', () {
      writePrePushHook(ggHook);
      writeVerifyPush();

      final removed = removeLegacyGitHooks(
        repoDir: repoDir,
        ggLog: messages.add,
      );

      expect(removed, isTrue);
      expect(prePushHook().existsSync(), isFalse);
      expect(verifyPush().existsSync(), isFalse);
      expect(
        messages,
        contains('Removed the obsolete gg pre-push hook from my_repo.'),
      );
    });

    test('keeps a custom pre-push hook that gg did not generate', () {
      writePrePushHook('#!/bin/sh\necho "my own hook"');

      final removed = removeLegacyGitHooks(
        repoDir: repoDir,
        ggLog: messages.add,
      );

      expect(removed, isFalse);
      expect(prePushHook().existsSync(), isTrue);
      expect(
        messages,
        contains(
          'Keeping the custom pre-push hook of my_repo — it is not the hook '
          'generated by gg.',
        ),
      );
    });

    test('removes verify_push.dart even when the hook is a custom one', () {
      writePrePushHook('#!/bin/sh\necho "my own hook"');
      writeVerifyPush();

      final removed = removeLegacyGitHooks(
        repoDir: repoDir,
        ggLog: messages.add,
      );

      expect(removed, isTrue);
      expect(prePushHook().existsSync(), isTrue);
      expect(verifyPush().existsSync(), isFalse);
    });

    test('removes the hook when verify_push.dart is already gone', () {
      writePrePushHook(ggHook);

      final removed = removeLegacyGitHooks(
        repoDir: repoDir,
        ggLog: messages.add,
      );

      expect(removed, isTrue);
      expect(prePushHook().existsSync(), isFalse);
    });

    test('does nothing and stays silent when no hook is installed', () {
      final removed = removeLegacyGitHooks(
        repoDir: repoDir,
        ggLog: messages.add,
      );

      expect(removed, isFalse);
      expect(messages, isEmpty);
    });
  });
}
